In [1]:
import sklearn

In [2]:
sklearn.__version__

'1.3.0'

In [3]:
from sklearn.datasets import load_iris #아이리스 데이터셋 가져오기
from sklearn.tree import DecisionTreeClassifier #분류형 모델 (#회귀형 모델은 DecisionTreeRegressor)
from sklearn.model_selection import train_test_split #데이터를 학습에 쓰일곳과 평가를 하는데 쓰일곳으로 분리할 수 있게 한다.
import pandas as pd

iris = load_iris()
type(iris) #bunch = dictionary
iris['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [5]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [6]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [7]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [8]:
iris_df = pd.DataFrame(data = iris.data,columns = iris.feature_names)

In [9]:
iris_df['label'] = iris.target

In [10]:
iris_df.sample(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
108                6.7               2.5                5.8               1.8   
144                6.7               3.3                5.7               2.5   
142                5.8               2.7                5.1               1.9   
16                 5.4               3.9                1.3               0.4   
128                6.4               2.8                5.6               2.1   

     label  
108      2  
144      2  
142      2  
16       0  
128      2

In [11]:
#test_size + train_size = 1, random_state : suffle이 True일 때 난수값, shuffle : 데이터를suffle 설정, stratify : 
X_train,X_test,y_train,y_test = train_test_split(iris.data,
                 iris.target,
                 test_size = 0.2, #8:2로 분리
                 random_state=11
) 

In [12]:
#max_depth : 트리의 깊이
#criterion : 샘플을 분류할 조건
#min_samples_split : 샘플을 나누기 위한 최소개수(최소2개) -> 최소개수보다 같거나 많으면 샘플을 분리한다.
dt_clf = DecisionTreeClassifier(random_state=11)
dt_clf.fit(X_train,y_train) #훈련시킴
pred = dt_clf.predict(X_test) #예측값 저장

In [13]:
y_test,pred #실제 데이터와 예측값 비교

(array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
        0, 1, 0, 0, 2, 1, 0, 1]),
 array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
        0, 1, 0, 0, 2, 1, 0, 1]))

In [14]:
from sklearn.metrics import accuracy_score

In [15]:
accuracy_score(y_test,pred) # 정확도 체크

0.9333333333333333

In [16]:
from sklearn.model_selection import KFold #kfold 방식으로 모델 검증
import numpy as np



In [17]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)
print('붓꽃 데이터 세트 크기:',iris.data.shape[0])

붓꽃 데이터 세트 크기: 150


In [18]:
kfold = KFold(n_splits = 5,shuffle=True,random_state=None) #train 데이터를 5개로 나눠 각각 1번씩 데이터검증(총 5번검증)
n_iter = 0
cv_accuracy = [] #각각의 검증 정확도를 저장할 리스트
for train_index, test_index in kfold.split(iris.data): #훈련시킬 데이터의 인덱스, 검증할 데이터의 인덱스
    #print(train_index)
    #print(test_index)
    X_train,X_test= iris.data[train_index],iris.data[test_index]
    y_train,y_test = iris.target[train_index],iris.target[test_index]
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test,pred),4)
    cv_accuracy.append(accuracy)
print('정확도:',cv_accuracy)
print('평균정확도:',np.mean(cv_accuracy))

#shuffle = False:
# 정확도: [1.0, 0.9667, 0.8667, 0.9333, 0.7333]
# 평균정확도: 0.9

#shuffle = True :
# 정확도: [1.0, 0.8333, 0.9667, 0.9333, 0.9667]
# 평균정확도: 0.9400000000000001




정확도: [0.9667, 1.0, 0.9, 0.9333, 0.9667]
평균정확도: 0.9533400000000001


In [19]:
from sklearn.model_selection import StratifiedKFold

In [20]:
kfold = StratifiedKFold(n_splits=3,shuffle=False)
n_iter = 0
for train_index, test_index in kfold.split(iris.data,iris_df['label']):
    #startifiedkfold에서는 y값이 반드시 필요(비율계산)
    n_iter+=1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print('## 교차검증:{0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n',label_train.value_counts())
    print('검증 레이블 데이터 분포:\n',label_test.value_counts())


## 교차검증:1
학습 레이블 데이터 분포:
 label
2    34
0    33
1    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    17
1    17
2    16
Name: count, dtype: int64
## 교차검증:2
학습 레이블 데이터 분포:
 label
1    34
0    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    17
2    17
1    16
Name: count, dtype: int64
## 교차검증:3
학습 레이블 데이터 분포:
 label
0    34
1    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
1    17
2    17
0    16
Name: count, dtype: int64


In [21]:
cv_accuracy = [] #각각의 검증 정확도를 저장할 리스트
kfold = StratifiedKFold(n_splits=5,shuffle=False)
for train_index, test_index in kfold.split(iris.data,iris_df['label']):
    X_train,X_test= iris.data[train_index],iris.data[test_index]
    y_train,y_test = iris.target[train_index],iris.target[test_index]
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    accuracy = np.round(accuracy_score(y_test,pred),4)
    cv_accuracy.append(accuracy)
print('정확도:',cv_accuracy)
print('평균정확도:',np.mean(cv_accuracy))



정확도: [0.9667, 0.9667, 0.9, 0.9667, 1.0]
평균정확도: 0.9600200000000001


In [22]:
from sklearn.model_selection import cross_val_score

In [25]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state = 156)
scores = cross_val_score(dt_clf,iris.data,iris.target,cv=3,scoring='accuracy') #cv : 교차검증 폴드 수
print('교차 검증별 정확도:',np.round(scores,4))
print('평균 검증 정확도:',np.round(np.mean(scores),4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


In [27]:
from sklearn.linear_model import LinearRegression #선형회귀분석

In [28]:
LinearRegression()
#fit_intercept=True : b값도 찾는다. 


LinearRegression()