In [1]:
#레이블 인코딩,원핫인코딩

In [2]:
from sklearn.preprocessing import LabelEncoder

In [3]:
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서'] 
#중복되는 값을 제외하고 종류별로 index를 붙여준다.
encoder = LabelEncoder()
encoder.fit(items)
print(encoder.classes_) # 만들어진 목록을 확인

['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [4]:
items_trans = encoder.transform(items) #각 항목에 인덱스를 붙인 결과
items_trans

array([0, 1, 4, 5, 3, 3, 2, 2])

In [5]:
encoder.inverse_transform(items_trans) #다시 원래대로 돌리기

array(['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'], dtype='<U5')

In [6]:
#원핫 인코딩
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [7]:
items

['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

In [8]:
encoder = LabelEncoder()
encoder.fit(items)
items_trans=encoder.transform(items)

In [9]:
items_trans.reshape(-1,1)

array([[0],
       [1],
       [4],
       [5],
       [3],
       [3],
       [2],
       [2]])

In [10]:
oh_encoder = OneHotEncoder(sparse_output=False)
oh_encoder.fit(items_trans.reshape(-1,1))
#각 데이터마다 희소한값을 고르고 2차원배열로 만들어 행마다 각 데이터가 존재하면 1 없으면 0으로 표시한다.

OneHotEncoder(sparse_output=False)

In [11]:
oh_encoder.transform(items_trans.reshape(-1,1))

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [12]:
import pandas as pd

In [13]:
df =pd.DataFrame({'item':items})
df

item
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서

In [14]:
pd.get_dummies(df,dtype=int)
#pandas의 get_dummis함수로 oneHotEncoder를 바로 진행할 수 있다.

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

In [15]:
from sklearn.datasets import load_iris
import pandas as pd

In [16]:
iris = load_iris()
iris_df = pd.DataFrame(data = iris.data,columns=iris.feature_names)

In [17]:
iris_df.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [18]:
iris_df.var()

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [19]:
iris_df.min()

sepal length (cm)    4.3
sepal width (cm)     2.0
petal length (cm)    1.0
petal width (cm)     0.1
dtype: float64

In [20]:
iris_df.max()

sepal length (cm)    7.9
sepal width (cm)     4.4
petal length (cm)    6.9
petal width (cm)     2.5
dtype: float64

In [21]:
from sklearn.preprocessing import StandardScaler #데이터 표준화(평균이 0, 분산이 1인 데이터로 변환)

In [22]:
s_scaler = StandardScaler()
iris_df_s = s_scaler.fit_transform(iris_df)
iris_df_s.mean()

-1.4684549872375404e-15

In [23]:
iris_df_s.var()

1.0

In [24]:
iris_df_s.std()

1.0

In [25]:
from sklearn.preprocessing import MinMaxScaler #최소값이 0 최대값이 1인 자료로 변환

In [26]:
m_scaler=MinMaxScaler()
iris_df_m= m_scaler.fit_transform(iris_df)

In [27]:
iris_df_m.min()

0.0

In [28]:
iris_df_m.max()

1.0

In [29]:
iris_df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [30]:
import numpy as np

In [37]:
train = np.arange(0,11).reshape(-1,1)
test = np.arange(0,12).reshape(-1,1)

In [38]:
train

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [39]:
scaler_m = MinMaxScaler()
scaler_m.fit(train)

MinMaxScaler()

In [40]:
scaler_m.transform(train).reshape(-1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [41]:
scaler_m.transform(test).reshape(-1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1])

In [42]:
scaler_m.fit_transform(test).reshape(-1) #처음 훈련시킨 모델을 다른 데이터에 적용시키면 결과가 달라진다.

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])